/**
 * كل نصوص الواجهة العربية بمكان واحد.
 * الفايدة: تعديل أي نص من مكان واحد، وسهولة إضافة لغة ثانية لاحقاً بدون تفتيش بالـ JSX.
 */
export const t = {
  app: {
    name: "فيورا",
  },

  nav: {
    logout: "تسجيل الخروج",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    collapse: "طيّ القائمة",
    expand: "توسيع القائمة",
    notifications: "الإشعارات",
  },

  common: {
    add: "إضافة",
    edit: "تعديل",
    cancel: "إلغاء",
    delete: "حذف",
    close: "إغلاق",
    save: "حفظ التغييرات",
    saved: "تم الحفظ بنجاح",
    loading: "جارٍ التحميل...",
    active: "نشط",
    inactive: "متوقف",
    currency: "₪",
    retry: "إعادة المحاولة",
    back: "رجوع",
    saving: "جارٍ الحفظ...",
    nothingChanged: "ما في أي تغيير للحفظ",
    remove: "إزالة",
    moveUp: "تحريك لفوق",
    moveDown: "تحريك لتحت",
    page: "صفحة",
    prev: "السابق",
    next: "التالي",
  },

  auth: {
    /*
      المستهلك الوحيد AuthContext — رسائل الطرد لما GET /auth/me يرفض.
      لوحة التاجر عندها البلوك كامل (شاشات دخول وتسجيل واسترجاع كلمة مرور)؛
      هون بس التلاتة اللي الحارس بيستعملهن.
    */
    notMerchant: "هذا الحساب زبون مش تاجر — لوحة التحكم للتجّار بس.",
    sessionExpired: "انتهت الجلسة. سجّل دخولك من جديد.",
    suspended: "هذا الحساب موقوف.",
  },

  dashboard: {
    /** مستهلكها الوحيد StatCard — بطاقات النظرة العامة */
    vsLastMonth: "مقارنة بالشهر الماضي",
  },

  errors: {
    notFoundTitle: "الصفحة غير موجودة",
    notFoundBody: "الرابط اللي فتحته مش موجود أو تم نقله.",
    backHome: "العودة للرئيسية",
    genericTitle: "صار خطأ غير متوقع",
    genericBody: "جرّب تحديث الصفحة، وإذا استمرت المشكلة تواصل مع الدعم.",
    retry: "إعادة المحاولة",
  },
  // ─── لوحة مالك المنصة ────────────────────────────────────────
  admin: {
    tagline: "لوحة مالك المنصة",
    owner: "مالك المنصة",
    ownerRole: "مشرف المنصة",

    nav: {
      dashboard: "نظرة عامة",
      stores: "المتاجر",
      users: "المستخدمون",
      categories: "التصنيفات",
      reports: "البلاغات",
      content: "المحتوى",
      delivery: "التوصيل",
    },

    common: {
      search: "بحث",
      clearSearch: "مسح البحث",
      noResults: "ما في نتائج مطابقة",
      noResultsHint: "جرّب كلمة بحث ثانية أو امسح الفلاتر.",
      all: "الكل",
      loadFailed: "ما قدرنا نجيب البيانات. جرّب مرة ثانية.",
      sessionInvalid: "الجلسة غير صالحة — سجّل دخولك من جديد.",
      backToList: "رجوع للقائمة",
      notFound: "العنصر غير موجود",
      notFoundHint: "الرابط اللي فتحته مش موجود أو تم حذفه.",
      reason: "السبب",
      reasonLabel: "سبب الإجراء",
      reasonPlaceholder: "اكتب سبباً واضحاً — بينحفظ بسجل التدقيق على السيرفر",
      reasonRequired: "لازم تكتب سبب الإجراء",
      reasonTooShort: "السبب لازم يكون 10 أحرف على الأقل",
      reasonTooLong: "السبب أطول من 500 حرف",
      none: "—",
      by: "بواسطة",
      createdAt: "تاريخ الإنشاء",
      openDetails: "عرض التفاصيل",
      mockNotice: "بيانات تجريبية — لسا ما تم ربط مسارات الأدمن بالباك إند.",
    },

    status: {
      active: "نشط",
      suspended: "موقوف",
      pending: "بانتظار التوثيق",
      open: "مفتوح",
      resolved: "تمت المعالجة",
      dismissed: "مرفوض",
    },

    dashboard: {
      title: "نظرة عامة على المنصة",
      subtitle: "إحصائيات المتاجر والمستخدمين والطلبات.",
      range7: "آخر 7 أيام",
      range30: "آخر 30 يوم",
      range90: "آخر 90 يوم",
      rangeLabel: "المدى الزمني",
      activeStores: "المتاجر النشطة",
      pendingStores: "بانتظار التوثيق",
      customers: "العملاء",
      merchants: "التجار",
      orders: "إجمالي الطلبات",
      gmv: "القيمة الإجمالية",
      openReports: "بلاغات مفتوحة",
      storeUnit: "متجر",
      userUnit: "مستخدم",
      orderUnit: "طلب",
      reportUnit: "بلاغ",
      growthTitle: "نمو التسجيلات",
      growthCustomers: "عملاء",
      growthMerchants: "تجار",
      ordersTrendTitle: "حركة الطلبات",
      ordersTrendSeries: "عدد الطلبات",
      topStores: "أعلى المتاجر",
      topStoresEmpty: "ما في متاجر لعرضها بعد",
      colStore: "المتجر",
      colOrders: "الطلبات",
      colRevenue: "الإيرادات",
      empty: "ما في بيانات بعد",
      emptyHint: "لما تبدأ المتاجر تستقبل طلبات رح تظهر الإحصائيات هون.",
    },

    stores: {
      title: "إدارة المتاجر",
      subtitle: "عرض المتاجر وتوثيقها وإيقافها.",
      count: "متجر",
      searchPlaceholder: "ابحث باسم المتجر أو المدينة أو المالك",
      empty: "ما في متاجر",
      emptyHint: "لما يسجّل تاجر ويفتح متجره رح يظهر هون.",
      colStore: "المتجر",
      colOwner: "المالك",
      colCity: "المدينة",
      colProducts: "المنتجات",
      colOrders: "الطلبات",
      colStatus: "الحالة",
      colCreated: "تاريخ الإنشاء",
      verified: "موثّق",
      unverified: "غير موثّق",
      detailsTitle: "تفاصيل المتجر",
      info: "بيانات المتجر",
      ownerInfo: "بيانات المالك",
      stats: "إحصائيات",
      description: "الوصف",
      phone: "الهاتف",
      address: "العنوان",
      city: "المدينة",
      categories: "التصنيفات",
      email: "البريد الإلكتروني",
      ownerStatus: "حالة حساب المالك",
      viewOwner: "عرض حساب المالك",
      productsUnit: "منتج",
      ordersUnit: "طلب",
      revenue: "الإيرادات",
      rating: "متوسط التقييم",
      reviewsUnit: "تقييم",
      noRating: "ما في تقييمات",
      verifiedAt: "تاريخ التوثيق",
      suspensionInfo: "معلومات الإيقاف",
      verify: "توثيق المتجر",
      unverify: "إلغاء التوثيق",
      suspend: "إيقاف المتجر",
      reactivate: "إعادة التفعيل",
      verifyTitle: "توثيق المتجر؟",
      verifyBody: "رح يظهر المتجر كموثّق للزبائن.",
      unverifyTitle: "إلغاء توثيق المتجر؟",
      unverifyBody: "رح تنشال علامة التوثيق من صفحة المتجر.",
      suspendTitle: "إيقاف المتجر",
      suspendBody:
        "رح ينحجب المتجر ومنتجاته عن الزبائن. السبب إلزامي وبينحفظ بسجل التدقيق.",
      reactivateTitle: "إعادة تفعيل المتجر؟",
      reactivateBody: "رح يرجع المتجر ومنتجاته يظهروا للزبائن.",
      didVerify: "تم توثيق المتجر",
      didUnverify: "تم إلغاء التوثيق",
      didSuspend: "تم إيقاف المتجر",
      didReactivate: "تم إعادة تفعيل المتجر",
    },

    users: {
      title: "إدارة المستخدمين",
      subtitle: "العملاء والتجار المسجّلون بالمنصة.",
      count: "مستخدم",
      searchPlaceholder: "ابحث بالاسم أو البريد أو رقم الهاتف",
      empty: "ما في مستخدمين",
      emptyHint: "لما يسجّل أول مستخدم رح يظهر هون.",
      merchant: "تاجر",
      customer: "زبون",
      colUser: "المستخدم",
      colRole: "الدور",
      colStore: "المتجر",
      colOrders: "الطلبات",
      colStatus: "الحالة",
      colCreated: "تاريخ التسجيل",
      detailsTitle: "تفاصيل المستخدم",
      account: "بيانات الحساب",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      role: "الدور",
      emailVerified: "البريد موثّق",
      emailNotVerified: "البريد غير موثّق",
      lastLogin: "آخر دخول",
      neverLoggedIn: "ما سجّل دخول بعد",
      store: "متجره",
      viewStore: "عرض المتجر",
      noStore: "ما عنده متجر",
      suspend: "إيقاف الحساب",
      reactivate: "إعادة تفعيل الحساب",
      suspendTitle: "إيقاف الحساب",
      suspendBody:
        "رح يُمنع المستخدم من الدخول. السبب إلزامي وبينحفظ بسجل التدقيق.",
      reactivateTitle: "إعادة تفعيل الحساب؟",
      reactivateBody: "رح يقدر المستخدم يسجّل دخول من جديد.",
      didSuspend: "تم إيقاف الحساب",
      didReactivate: "تم إعادة تفعيل الحساب",
      duplicateEmailNote:
        "نفس البريد ممكن يكون مسجّل مرتين — مرة كزبون ومرة كتاجر — وهاي حسابات منفصلة تماماً.",
    },

    categories: {
      title: "إدارة التصنيفات",
      subtitle: "شجرة تصنيفات المنصة المستخدمة بالمنتجات.",
      empty: "ما في تصنيفات",
      emptyHint: "أضف أول تصنيف رئيسي عشان يقدر التجار يصنّفوا منتجاتهم.",
      addRoot: "تصنيف رئيسي",
      addChild: "تصنيف فرعي",
      editRoot: "تعديل التصنيف الرئيسي",
      editChild: "تعديل التصنيف الفرعي",
      newRoot: "تصنيف رئيسي جديد",
      newChild: "تصنيف فرعي جديد",
      name: "الاسم",
      namePlaceholder: "مثال: ملابس رجالية",
      imageUrl: "رابط الصورة",
      imageUrlPlaceholder: "https://...",
      sizeGroup: "مجموعة المقاسات",
      sizeGroupPlaceholder: "اختر مجموعة المقاسات",
      sizeGroupHint:
        "بتحدّد المقاسات المتاحة للمنتجات تحت هذا التصنيف — ما بتنغيّر بعد الإنشاء.",
      productsUnit: "منتج",
      noChildren: "ما في تصنيفات فرعية",
      expand: "فتح التصنيف",
      collapse: "طيّ التصنيف",
      created: "تم إنشاء التصنيف",
      updated: "تم تعديل التصنيف",
      nameRequired: "الاسم لازم يكون من حرفين لـ 60",
      sizeGroupRequired: "اختر مجموعة المقاسات",
      deleteNote: "الحذف غير متاح حالياً — قواعده لسا ما تحدّدت مع الباك إند.",
    },

    sizeGroups: {
      CLOTHING: "ملابس",
      SHOES: "أحذية",
      KIDS: "أطفال",
      ONE_SIZE: "مقاس واحد",
    },

    reports: {
      title: "البلاغات والشكاوى",
      subtitle: "البلاغات على التقييمات والمنتجات والمتاجر.",
      count: "بلاغ",
      searchPlaceholder: "ابحث بسبب البلاغ أو اسم المبلّغ",
      empty: "ما في بلاغات",
      emptyHint: "لما يبلّغ زبون عن محتوى مخالف رح يظهر البلاغ هون.",
      colTarget: "النوع",
      colPreview: "المحتوى",
      colReason: "سبب البلاغ",
      colReporter: "المبلّغ",
      colStatus: "الحالة",
      colCreated: "تاريخ البلاغ",
      targetReview: "تقييم",
      targetProduct: "منتج",
      targetStore: "متجر",
      detailsTitle: "تفاصيل البلاغ",
      reportInfo: "بيانات البلاغ",
      reportedContent: "المحتوى المبلّغ عنه",
      reporter: "المبلّغ",
      reportReason: "سبب البلاغ",
      note: "ملاحظة المشرف",
      relatedCount: "بلاغ سابق على نفس الهدف",
      reviewOnProduct: "تقييم منتج",
      reviewOnStore: "تقييم متجر",
      reviewBy: "كتبه",
      reviewRating: "التقييم",
      hiddenBadge: "مخفي عن الزبائن · ظاهر للتاجر",
      hiddenReason: "سبب الإخفاء",
      hiddenAt: "تاريخ الإخفاء",
      hide: "إخفاء التقييم",
      unhide: "إلغاء الإخفاء",
      hideTitle: "إخفاء التقييم",
      hideBody:
        "التقييم رح ينحجب عن الزبائن، وبيضل ظاهر للتاجر. السبب إلزامي وبينحفظ بسجل التدقيق.",
      unhideTitle: "إلغاء إخفاء التقييم؟",
      unhideBody: "رح يرجع التقييم يظهر للزبائن.",
      resolve: "تعليم كمعالج",
      dismiss: "رفض البلاغ",
      resolveTitle: "تعليم البلاغ كمعالج؟",
      resolveBody: "بيتوثّق إنه تم اتخاذ إجراء بخصوص هذا البلاغ.",
      dismissTitle: "رفض البلاغ؟",
      dismissBody: "بيتوثّق إنه ما في مخالفة بهذا المحتوى.",
      viewProduct: "عرض المنتج",
      viewStore: "عرض المتجر",
      didHide: "تم إخفاء التقييم عن الزبائن",
      didUnhide: "تم إلغاء إخفاء التقييم",
      didResolve: "تم تعليم البلاغ كمعالج",
      didDismiss: "تم رفض البلاغ",
      contentGone: "المحتوى المبلّغ عنه لم يعد موجوداً",
    },

    content: {
      title: "إدارة المحتوى",
      subtitle: "محتوى الصفحة الرئيسية والصفحات الثابتة والإعلانات.",
      tabHome: "الصفحة الرئيسية",
      tabPages: "الصفحات الثابتة",
      tabBanners: "الإعلانات",
      heroTitle: "عنوان الواجهة",
      heroSubtitle: "العنوان الفرعي",
      heroImage: "صورة الواجهة",
      featuredStores: "متاجر مميّزة",
      featuredCategories: "تصنيفات مميّزة",
      featuredHint:
        "أرقام المعرّفات مفصولة بفاصلة — مؤقتاً لحد ما يوصل مسار الاختيار من الباك إند.",
      featuredInvalid: "أدخل أرقام معرّفات صحيحة مفصولة بفاصلة",
      pageTitle: "عنوان الصفحة",
      pageBody: "نص الصفحة",
      preview: "معاينة",
      previewEmpty: "اكتب نص الصفحة عشان تشوف المعاينة.",
      terms: "شروط الاستخدام",
      privacy: "سياسة الخصوصية",
      about: "من نحن",
      lastUpdated: "آخر تعديل",
      bannersEmpty: "ما في إعلانات",
      bannersEmptyHint: "أضف إعلاناً مصوّراً عشان يظهر بالصفحة الرئيسية.",
      addBanner: "إضافة إعلان",
      editBanner: "تعديل الإعلان",
      newBanner: "إعلان جديد",
      bannerTitle: "عنوان الإعلان",
      bannerImage: "صورة الإعلان",
      bannerLink: "رابط الوجهة",
      bannerLinkPlaceholder: "https://...",
      bannerPosition: "الترتيب",
      bannerActive: "مفعّل",
      bannerStarts: "يبدأ بتاريخ",
      bannerEnds: "ينتهي بتاريخ",
      bannerImageRequired: "أضف صورة الإعلان",
      bannerTitleRequired: "أدخل عنوان الإعلان",
      deleteBannerTitle: "حذف الإعلان؟",
      deleteBannerBody: "رح ينشال الإعلان من الصفحة الرئيسية نهائياً.",
      bannerSaved: "تم حفظ الإعلان",
      bannerDeleted: "تم حذف الإعلان",
      titleRequired: "أدخل عنوان الصفحة",
      bodyRequired: "أدخل نص الصفحة",
      bodyTooLong: "النص أطول من الحد المسموح",
    },

    delivery: {
      title: "تكامل التوصيل",
      subtitle: "حالة التكامل مع شركة التوصيل وآخر حالات الفشل.",
      provider: "المزوّد",
      health: "حالة التكامل",
      up: "يعمل",
      degraded: "متقطّع",
      down: "متوقف",
      lastCheck: "آخر فحص",
      successRate: "نسبة النجاح (24 ساعة)",
      avgResponse: "متوسط زمن الاستجابة",
      failures24h: "حالات فشل (24 ساعة)",
      failuresTitle: "آخر حالات الفشل",
      colTime: "الوقت",
      colOrder: "الطلب",
      colEndpoint: "المسار",
      colStatus: "الكود",
      colMessage: "الرسالة",
      retryable: "قابل لإعادة المحاولة",
      empty: "ما في حالات فشل مسجّلة",
      emptyHint: "التكامل شغّال بلا أخطاء بآخر فترة.",
      refresh: "تحديث",
      readOnlyNote:
        "شاشة مراقبة للقراءة فقط — إعادة إرسال الطلبات الفاشلة بتحتاج قرار وصلاحية من الباك إند.",
    },
  },
} as const;
