import type { SizeGroup } from "./types";

export interface CatalogSeedChild {
  name: string;
  sizeGroup: SizeGroup;
}

export interface CatalogSeedRoot {
  name: string;
  children: CatalogSeedChild[];
}

export const INITIAL_CATALOG_DATA: readonly CatalogSeedRoot[] = [
  {
    name: "ملابس نسائية",
    children: [
      { name: "بلايز", sizeGroup: "CLOTHING" },
      { name: "قمصان", sizeGroup: "CLOTHING" },
      { name: "تيشرتات", sizeGroup: "CLOTHING" },
      { name: "توب", sizeGroup: "CLOTHING" },
      { name: "كروب توب", sizeGroup: "CLOTHING" },
      { name: "تونيك", sizeGroup: "CLOTHING" },
      { name: "جاكيتات", sizeGroup: "CLOTHING" },
      { name: "ترانش", sizeGroup: "CLOTHING" },
      { name: "معطف", sizeGroup: "CLOTHING" },
      { name: "بليزر", sizeGroup: "CLOTHING" },
      { name: "كارديغان", sizeGroup: "CLOTHING" },
      { name: "فيست", sizeGroup: "CLOTHING" },
      { name: "فساتين (يومي، سهرة، رسمي، طويل، قصير، ميدي، محتشم)", sizeGroup: "CLOTHING" },
      { name: "جلبابات", sizeGroup: "CLOTHING" },
      { name: "عبايات", sizeGroup: "CLOTHING" },
      { name: "قفطان", sizeGroup: "CLOTHING" },
      { name: "تونيك طويل", sizeGroup: "CLOTHING" },
      { name: "أطقم (بنطال، تنورة، صيفي، شتوي، ترنقات منزلية)", sizeGroup: "CLOTHING" },
      { name: "بناطيل", sizeGroup: "CLOTHING" },
      { name: "تنانير", sizeGroup: "CLOTHING" },
      { name: "شورتات", sizeGroup: "CLOTHING" },
      { name: "جينز", sizeGroup: "CLOTHING" },
      { name: "ليقنز", sizeGroup: "CLOTHING" },
      { name: "بيجامات", sizeGroup: "CLOTHING" },
      { name: "أرواب", sizeGroup: "CLOTHING" },
      { name: "ملابس منزلية", sizeGroup: "CLOTHING" },
      { name: "ملابس نوم", sizeGroup: "CLOTHING" },
    ],
  },
  {
    name: "ملابس رجالية",
    children: [
      { name: "تيشرت", sizeGroup: "CLOTHING" },
      { name: "قميص", sizeGroup: "CLOTHING" },
      { name: "سويت تيشرت", sizeGroup: "CLOTHING" },
      { name: "هودي", sizeGroup: "CLOTHING" },
      { name: "بنطال", sizeGroup: "CLOTHING" },
      { name: "جينز", sizeGroup: "CLOTHING" },
      { name: "شورت", sizeGroup: "CLOTHING" },
      { name: "جاكيت", sizeGroup: "CLOTHING" },
      { name: "بليزر", sizeGroup: "CLOTHING" },
      { name: "معطف", sizeGroup: "CLOTHING" },
      { name: "فيست", sizeGroup: "CLOTHING" },
      { name: "بيجامة", sizeGroup: "CLOTHING" },
      { name: "ملابس رسمية (بدلة، بنطال رسمي، قميص رسمي، ربطة عنق)", sizeGroup: "CLOTHING" },
      { name: "ملابس رياضية", sizeGroup: "CLOTHING" },
      { name: "أطقم منزلية (ترنقات)", sizeGroup: "CLOTHING" },
    ],
  },
  {
    name: "أطفال ومحير - بنات",
    children: [
      { name: "فساتين", sizeGroup: "KIDS" },
      { name: "تيشرتات", sizeGroup: "KIDS" },
      { name: "بلوزة", sizeGroup: "KIDS" },
      { name: "قميص", sizeGroup: "KIDS" },
      { name: "تنورة", sizeGroup: "KIDS" },
      { name: "بنطال", sizeGroup: "KIDS" },
      { name: "جينز", sizeGroup: "KIDS" },
      { name: "شورت", sizeGroup: "KIDS" },
      { name: "أطقم", sizeGroup: "KIDS" },
      { name: "جاكيت", sizeGroup: "KIDS" },
      { name: "معطف", sizeGroup: "KIDS" },
      { name: "هودي", sizeGroup: "KIDS" },
      { name: "سويت شيرت", sizeGroup: "KIDS" },
      { name: "أطقم منزلية", sizeGroup: "KIDS" },
      { name: "أطقم رياضية", sizeGroup: "KIDS" },
      { name: "بيجامات", sizeGroup: "KIDS" },
      { name: "ملابس تنكرية", sizeGroup: "KIDS" },
    ],
  },
  {
    name: "أطفال ومحير - أولاد",
    children: [
      { name: "هودي", sizeGroup: "KIDS" },
      { name: "تيشرتات", sizeGroup: "KIDS" },
      { name: "بلوزة", sizeGroup: "KIDS" },
      { name: "قميص", sizeGroup: "KIDS" },
      { name: "بنطال", sizeGroup: "KIDS" },
      { name: "جينز", sizeGroup: "KIDS" },
      { name: "شورت", sizeGroup: "KIDS" },
      { name: "أطقم", sizeGroup: "KIDS" },
      { name: "جاكيت", sizeGroup: "KIDS" },
      { name: "معطف", sizeGroup: "KIDS" },
      { name: "سويت شيرت", sizeGroup: "KIDS" },
      { name: "أطقم منزلية", sizeGroup: "KIDS" },
      { name: "أطقم رياضية", sizeGroup: "KIDS" },
      { name: "بيجامات", sizeGroup: "KIDS" },
      { name: "ملابس تنكرية", sizeGroup: "KIDS" },
    ],
  },
  {
    name: "ملابس المواليد والرضع",
    children: [
      { name: "أطقم مواليد", sizeGroup: "KIDS" },
      { name: "سالوبيت (تبان / رومبير)", sizeGroup: "KIDS" },
      { name: "تيشرت", sizeGroup: "KIDS" },
      { name: "بلوزة", sizeGroup: "KIDS" },
      { name: "بنطال", sizeGroup: "KIDS" },
      { name: "شورت", sizeGroup: "KIDS" },
      { name: "تنورة", sizeGroup: "KIDS" },
      { name: "فستان", sizeGroup: "KIDS" },
      { name: "كيس نوم", sizeGroup: "ONE_SIZE" },
      { name: "بطانيات ولفافات", sizeGroup: "ONE_SIZE" },
      { name: "جاكيت", sizeGroup: "KIDS" },
      { name: "كنزة", sizeGroup: "KIDS" },
      { name: "أطقم شتوية", sizeGroup: "KIDS" },
      { name: "مرايل وبافتات", sizeGroup: "ONE_SIZE" },
      { name: "بدلات وغيارات", sizeGroup: "KIDS" },
      { name: "إكسسوارات المواليد (قبعة، قفازات، جوارب)", sizeGroup: "ONE_SIZE" },
      { name: "كلكولة (أحذية مواليد)", sizeGroup: "SHOES" },
    ],
  },
  {
    name: "متجر الأحذية",
    children: [
      { name: "كعب", sizeGroup: "SHOES" },
      { name: "صندل", sizeGroup: "SHOES" },
      { name: "شبشب", sizeGroup: "SHOES" },
      { name: "بوت", sizeGroup: "SHOES" },
      { name: "بوتين", sizeGroup: "SHOES" },
      { name: "لوفر", sizeGroup: "SHOES" },
      { name: "باليرينا وفلات (سكربينا)", sizeGroup: "SHOES" },
      { name: "حذاء رياضي", sizeGroup: "SHOES" },
      { name: "سنيكرز", sizeGroup: "SHOES" },
      { name: "كوتشي", sizeGroup: "SHOES" },
      { name: "سكيتشرز", sizeGroup: "SHOES" },
      { name: "أحذية طبية", sizeGroup: "SHOES" },
      { name: "أحذية شتوية", sizeGroup: "SHOES" },
      { name: "منتوفلي (حذاء منزلي)", sizeGroup: "SHOES" },
      { name: "حذاء رسمي رجالي", sizeGroup: "SHOES" },
      { name: "أحذية أطفال", sizeGroup: "SHOES" },
      { name: "كلكولة (أحذية مواليد)", sizeGroup: "SHOES" },
    ],
  },
  {
    name: "كوزماتيكس وإكسسوارات",
    children: [
      { name: "ساعات", sizeGroup: "ONE_SIZE" },
      { name: "عقد أو طقم مجوهرات", sizeGroup: "ONE_SIZE" },
      { name: "خاتم", sizeGroup: "ONE_SIZE" },
      { name: "قرط", sizeGroup: "ONE_SIZE" },
      { name: "خلخال", sizeGroup: "ONE_SIZE" },
      { name: "انسيال", sizeGroup: "ONE_SIZE" },
      { name: "بروش", sizeGroup: "ONE_SIZE" },
      { name: "سلاسل", sizeGroup: "ONE_SIZE" },
      { name: "نظارات", sizeGroup: "ONE_SIZE" },
      { name: "شال", sizeGroup: "ONE_SIZE" },
      { name: "خمار", sizeGroup: "ONE_SIZE" },
      { name: "بندانة", sizeGroup: "ONE_SIZE" },
      { name: "دبابيس حجاب", sizeGroup: "ONE_SIZE" },
      { name: "طاقية وقبعة", sizeGroup: "ONE_SIZE" },
      { name: "كاب", sizeGroup: "ONE_SIZE" },
      { name: "محافظ", sizeGroup: "ONE_SIZE" },
      { name: "عطور ومزيلات عرق", sizeGroup: "ONE_SIZE" },
      { name: "أطقم عطور (عطر ولوشن، عطر وبودي ميست)", sizeGroup: "ONE_SIZE" },
      { name: "حقيبة يد", sizeGroup: "ONE_SIZE" },
      { name: "حقيبة كتف", sizeGroup: "ONE_SIZE" },
      { name: "حقيبة ظهر", sizeGroup: "ONE_SIZE" },
      { name: "حقيبة خصر", sizeGroup: "ONE_SIZE" },
      { name: "حقيبة سفر", sizeGroup: "ONE_SIZE" },
      { name: "كلاتش", sizeGroup: "ONE_SIZE" },
      { name: "توت باج", sizeGroup: "ONE_SIZE" },
      { name: "كروكس", sizeGroup: "SHOES" },
      { name: "سكارف ووشاح", sizeGroup: "ONE_SIZE" },
      { name: "قفازات ومعاصم", sizeGroup: "ONE_SIZE" },
      { name: "إكسسوارات الشعر", sizeGroup: "ONE_SIZE" },
      { name: "أحزمة", sizeGroup: "ONE_SIZE" },
    ],
  },
  {
    name: "الميك اب والعناية بالتجميل",
    children: [
      { name: "غسول الوجه", sizeGroup: "ONE_SIZE" },
      { name: "مرطب البشرة", sizeGroup: "ONE_SIZE" },
      { name: "سيروم", sizeGroup: "ONE_SIZE" },
      { name: "واقي شمس", sizeGroup: "ONE_SIZE" },
      { name: "ماسك للوجه", sizeGroup: "ONE_SIZE" },
      { name: "مزيل الميك اب", sizeGroup: "ONE_SIZE" },
      { name: "برايمر", sizeGroup: "ONE_SIZE" },
      { name: "فاونديشن (كريم أساس)", sizeGroup: "ONE_SIZE" },
      { name: "كونسيلر", sizeGroup: "ONE_SIZE" },
      { name: "بودرة وجه", sizeGroup: "ONE_SIZE" },
      { name: "أحمر خدود (بلاشر)", sizeGroup: "ONE_SIZE" },
      { name: "هايلايتر", sizeGroup: "ONE_SIZE" },
      { name: "ظلال العيون (ايشادو)", sizeGroup: "ONE_SIZE" },
      { name: "ايلاينر", sizeGroup: "ONE_SIZE" },
      { name: "ماسكارا", sizeGroup: "ONE_SIZE" },
      { name: "كحل", sizeGroup: "ONE_SIZE" },
      { name: "قلم حواجب", sizeGroup: "ONE_SIZE" },
      { name: "احمر شفاه", sizeGroup: "ONE_SIZE" },
      { name: "ملمع شفاه", sizeGroup: "ONE_SIZE" },
      { name: "محدد شفاه", sizeGroup: "ONE_SIZE" },
      { name: "شامبو", sizeGroup: "ONE_SIZE" },
      { name: "بلسم", sizeGroup: "ONE_SIZE" },
      { name: "ماسكات وزيوت الشعر", sizeGroup: "ONE_SIZE" },
      { name: "منتجات تصفيف الشعر", sizeGroup: "ONE_SIZE" },
      { name: "لوشن الجسم", sizeGroup: "ONE_SIZE" },
      { name: "كريمات ومنتجات الاستحمام", sizeGroup: "ONE_SIZE" },
      { name: "فرش الميك اب والاسفنجات", sizeGroup: "ONE_SIZE" },
      { name: "مرايا", sizeGroup: "ONE_SIZE" },
      { name: "حقائب الميك اب", sizeGroup: "ONE_SIZE" },
    ],
  },
] as const;
